export const ORDER_TIMEOUT = {
  PENDING_PAYMENT_MINUTES: 30,
  PENDING_ACCEPT_HOURS: 2,
  PENDING_RECEIPT_DAYS: 3,
  AFTER_SALE_ALLOW_DAYS: 7,
};

export const DELIVERY = {
  AUTO_DISPATCH_RADIUS_KM: 5,
  DRIVER_RESPONSE_SECONDS: 30,
  AUTO_DISPATCH_BATCH_SIZE: 3,
};

export const COMMISSION = {
  DEFAULT_RATE: 0.03,
};

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
};
