apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lv-cube-miniapp
  labels:
    app: lv-cube-miniapp
    cloud.sealos.io/app-deploy-manager: lv-cube-miniapp
    cloud.sealos.io/app-deploy-manager-domain: lv-cube-h5-ns-0qkedm1h
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: lv-cube-h5-ns-0qkedm1h.cloud.sealos.io
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: lv-cube-miniapp
                port:
                  number: 80
  tls:
    - hosts:
        - lv-cube-h5-ns-0qkedm1h.cloud.sealos.io
      secretName: wildcard-cloud-sealos-io-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lv-cube-admin
  labels:
    app: lv-cube-admin
    cloud.sealos.io/app-deploy-manager: lv-cube-admin
    cloud.sealos.io/app-deploy-manager-domain: lv-cube-admin-ns-0qkedm1h
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: lv-cube-admin-ns-0qkedm1h.cloud.sealos.io
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: lv-cube-admin
                port:
                  number: 80
  tls:
    - hosts:
        - lv-cube-admin-ns-0qkedm1h.cloud.sealos.io
      secretName: wildcard-cloud-sealos-io-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lv-cube-server
  labels:
    app: lv-cube-server
    cloud.sealos.io/app-deploy-manager: lv-cube-server
    cloud.sealos.io/app-deploy-manager-domain: lv-cube-api-ns-0qkedm1h
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
spec:
  rules:
    - host: lv-cube-api-ns-0qkedm1h.cloud.sealos.io
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: lv-cube-server
                port:
                  number: 3000
  tls:
    - hosts:
        - lv-cube-api-ns-0qkedm1h.cloud.sealos.io
      secretName: wildcard-cloud-sealos-io-cert
